services:
  - type: web
    name: julien-serbanescu-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: COHERE_API_KEY
        sync: false
      - key: DEEPKEY
        sync: false
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 120"
    healthCheckPath: /api/query
    autoDeploy: true
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80 