services:
  - type: web
    name: julien-serbanescu-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: COHERE_API_KEY
        sync: false
      - key: DEEPKEY
        sync: false
    healthCheckPath: /api/query
    autoDeploy: true 